version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sims4-random-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1boxwv36sb7fx"
s3_prefix = "sims4-random-app"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
