Transform: AWS::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs16.x
      Handler: com.ms.sims4randomnizer.util.LambdaStreamHandler::handleRequest
      InlineCode: |
        exports.handler = async (event) => {
          console.log(event);
        }
