package com.ms.sims4randomnizer.model.enums;

public enum Aspiration {
    BODYBUILDER, PAINTER, MUSICAL_GENIUS, BESTSELLING_AUTHOR, PUBLIC_ENEMY, CHIEF_OF_MISCHIEF, VILLANOUS_VALENTINE,
    SUCCESSFUL_LINEAGE, BIG_HAPPY_FAMILY, MASTER_CHEF, MASTER_MIXOLOGIST, FABULOUSLY_WEALTHY, MANSION_BARON,
    RENAISSANCE_SIM, NERD_BRAIN, COMPUTER_WHIZ, SERIAL_ROMANTIC, SOULMATE, FREELANCE_BOTANIST, CURATOR, ANGLING_ACE,
    JOKE_STAR, PARTY_ANIMAL, FRIEND_OF_WORLD, NEIGHBORHOOD_CONFIDANTE
}
