package com.ms.sims4randomnizer.model.enums;

public enum Skill {

    CHARISMA, COMEDY, COOKING, FISHING, FITNESS, GARDENING, GOURMET_COOKING, GUITAR, HANDINESS, LOGIC, MISCHIEF,
    MIXOLOGY, PAINTING, PIANO, PHOTOGRAPHY, PROGRAMMING, ROCKET_SCIENCE, VIDEO_GAMING, VIOLIN, WRITING
}
